config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'residents#index'

  resources :addresses
  resources :residents

  post '/resident/:id/status' => 'residents#switch_status', as: 'status_resident'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :resident

  validates :cep, :street, :neighborhood, :city, :state, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resident.rb
class Resident < ApplicationRecord
  include Cns

  has_one :address
  has_one_attached :picture
  accepts_nested_attributes_for :address

  validates :full_name, :cpf, :cns, :email, :birth_date, :phone_number, presence: true
  validate :cpf_is_valid?, :email_is_valid?, :cns_is_valid?, :birth_date_valid?

  after_save :send_welcome

  def cpf_is_valid?
    return errors.add(:cpf, 'CPF inválido') unless CPF.valid?(cpf)
  end

  def email_is_valid?
    return errors.add(:email, 'Email inválido') unless email =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end

  def cns_is_valid?
    return errors.add(:cns, 'CNS inválido') unless Cns.validate(cns)
  end

  def birth_date_valid?
    return false if birth_date.empty?

    date_time = birth_date.to_datetime
    year = date_time.year
    actual_year = DateTime.now.year

    return errors.add(:birth_date, 'Data de nascimento inválida') if year > actual_year || (actual_year - year) > 120
  end

  def send_welcome
    Thread.new do
      ApplicationMailer.welcome(self).deliver_now!
      TwilioTextMessenger.new('Cadastro realizado com sucesso!', phone_number).call
    end
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]

  def index
    @addresses = Address.all
  end

  def show
  end

  def new
    @address = Address.new
  end

  def edit
  end

  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to address_url(@address), notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_address
    @address = Address.find(params[:id])
  end

  def address_params
    params.fetch(:address, {})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning, :success
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  before_action :set_resident, only: %i[show edit update destroy switch_status]

  def index
    if params[:search].present?
      @residents = Resident.joins(:address).where(
        'lower(addresses.city) LIKE ? OR lower(addresses.state) = ? OR residents.full_name LIKE ?',
        "%#{params[:search]}%".downcase, params[:search].downcase, "%#{params[:search]}%"
      ).includes(:address)
    else
      @residents = Resident.includes(:address).all
    end
  end

  def show; end

  def new
    @resident ||= Resident.new
    @resident.build_address
  end

  def create
    @resident = Resident.new(register_params)

    if @resident.save
      flash[:success] = 'Registro criado com sucesso!'
      redirect_to residents_path
    else
      flash[:danger] = @resident.errors.full_messages.to_sentence
      render :edit
    end
  end

  def update
    if @resident.update(register_params)
      flash[:success] = 'Registro atualizado com sucesso!'
      redirect_to residents_path
    else
      flash[:danger] = @resident.errors.full_messages.to_sentence
      redirect_to action: :edit
    end
  end

  def edit; end

  def switch_status
    @resident.active = !@resident.active
    if @resident.save
      flash[:success] = 'Status alterado com sucesso!'
      redirect_to residents_path
    else
      flash[:error] = 'Não foi possivel alterar o status!'
    end
  end

  private

  def set_resident
    @resident = Resident.find(params[:id])
  end

  def register_params
    params.require(:resident)
          .permit(:full_name, :cpf, :cns, :email, :birth_date, :phone_number, :picture,
                  address_attributes: %i[id cep street neighborhood city state complement])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jedis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>

  <% flash.each do |type, msg| %>
    <div class="alert alert-<%= type %>">
      <%= msg %>
    </div>
  <% end %>

  <%= yield %>
  </body>
</html>

<style>

  body {
    margin: 3%
  }
</style>

app/views/residents/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for @resident do |f| %>
      <div class="form">
        <div class="resident_form">
          <h3>Informações</h3>
          <div class="input">
            <label for="resident_full_name">
              Nome Completo
            </label>
            <%= f.text_field :full_name, placeholder: "John Doe", :required => true %>
          </div>

          <div class="input">
            <label for="resident_cpf">
              CPF
            </label>
            <%= f.text_field :cpf, placeholder: "000.000.000-00", :required => true %>
          </div>

          <div class="input">
            <label for="resident_cns">
              CNS
            </label>
            <%= f.text_field :cns, :required => true, :maxlength => 15 %>
          </div>

          <div class="input">
            <label for="resident_email">
              Email
            </label>
            <%= f.text_field :email, placeholder: "email@email.com", :required => true %>
          </div>

          <div class="input">
            <label for="resident_birth_date">
              Data de nascimento
            </label>
            <%= f.date_field :birth_date, value: @resident.birth_date, :required => true %>
          </div>

          <div class="input">
            <label for="resident_phone_number">
              Celular
            </label>
            <%= f.text_field :phone_number, placeholder: "99 99999-9999", :required => true %>
          </div>

          <div class="input">
            <label for="resident_picture">
              Foto
            </label>
            <%= f.file_field :picture, id: "imgInp", value: @resident.picture %>
            <% if @resident.picture.attached? %>
              <%= image_tag(@resident.picture, style: "height:200px") %>
            <% end %>
            <img id="preview" src="#" alt="your image" style="height: 200px"/>
          </div>
        </div>

        <div class="address_form">
          <h3>Endereço</h3>
          <%= f.fields_for :address do |address_form| %>
            <div class="input">
              <label for="resident_address_attributes_cep">
                CEP
              </label>
              <%= address_form.text_field :cep, :required => true %>
            </div>
            <div class="input">
              <label for="resident_address_attributes_street">
                Rua
              </label>
              <%= address_form.text_field :street %>
            </div>
            <div class="input">
              <label for="resident_address_attributes_neighborhood">
                Bairro
              </label>
              <%= address_form.text_field :neighborhood, :required => true %>
            </div>
            <div class="input">
              <label for="resident_address_attributes_city">
                Cidade
              </label>
              <%= address_form.text_field :city, :required => true %>
            </div>
            <div class="input">
              <label for="resident_address_attributes_state">
                UF
              </label>
              <%= address_form.text_field :state, :required => true %>
            </div>
            <div class="input">
              <label for="resident_address_attributes_complement">
                Complemento
              </label>
              <%= address_form.text_field :complement %>
            </div>
          <% end %>

        </div>
      </div>
      <div class="submit">
        <%= f.submit request.path.include?('new') ? "Criar Municipe" : "Editar Municipe" %>
      </div>

      <%= link_to "Menu", residents_path, id: "menu", class: 'btn btn-lg btn-default' %>
    <% end %>
  </div>
</div>

<style>

    #menu {
        text-align: center;
        margin: 0 auto;
    }

    .form {
        display: flex;
        justify-content: center;
    }

    .resident_form {
        margin-right: 50px
    }

    .address_form {
        margin-left: 50px
    }

    input {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 50%
    }

    .submit, #menu {
        display: flex;
        justify-content: center;
        text-decoration: none;
    }
</style>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>

<script>
    preview.style.display = "none";
    imgInp.onchange = evt => {
        const [file] = imgInp.files
        if (file) {
            preview.style.display = "block";
            preview.src = URL.createObjectURL(file)
        }
    }

    $(document).ready(function () {

        function limpa_formulário_cep() {
            $("input#resident_address_attributes_street").val("");
            $("input#resident_address_attributes_neighborhood").val("");
            $("input#resident_address_attributes_city").val("");
            $("input#resident_address_attributes_state").val("");
            // $("#ibge").val("");
        }

        $("input#resident_address_attributes_cep").blur(function () {
            var cep = $(this).val().replace(/\D/g, '');
            if (cep != "") {
                var validacep = /^[0-9]{8}$/;
                if (validacep.test(cep)) {
                    $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {

                        if (!("erro" in dados)) {
                            $("input#resident_address_attributes_street").val(dados.logradouro);
                            $("input#resident_address_attributes_neighborhood").val(dados.bairro);
                            $("input#resident_address_attributes_city").val(dados.localidade);
                            $("input#resident_address_attributes_state").val(dados.uf);

                            $("input#resident_address_attributes_street").attr('readonly', true);
                            $("input#resident_address_attributes_neighborhood").attr('readonly', true);
                            $("input#resident_address_attributes_city").attr('readonly', true);
                            $("input#resident_address_attributes_state").attr('readonly', true);
                        } else {
                            limpa_formulário_cep();
                            alert("CEP não encontrado.");
                        }
                    });
                } else {
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                }
            } else {
                limpa_formulário_cep();
            }
        });
    });

</script>

app/views/residents/edit.html.erb
<%= render "form" %>

app/views/residents/index.html.erb
<h1>Lista de Municipes</h1>

<%= form_with( url: residents_path ,method: :get , remote: true) do |f| %>
  <%= f.text_field :search, value: params[:search]  %>
  <%= f.submit "Pesquisar" %>
<% end %>
<br/>
<table id="residents">
  <tr>
    <th> ID</th>
    <th> Name</th>
    <th> CPF</th>
    <th> CNS</th>
    <th> Telefone</th>
    <th> Cidade</th>
    <th> UF</th>
    <th> Status</th>
    <th>Opções</th>
  </tr>
    <% @residents.each do |resident| %>
    <% address = resident.address %>
    <tr>
      <td><%= resident.id %></td>
      <td><%= resident.full_name %></td>
      <td><%= "#{resident.cpf.first(3)}.***.***-#{resident.cpf.last(2)}"%></td>
      <td><%= "#{resident.cns.first(3)}************"%></td>
      <td><%= "(#{resident.phone_number.first(2)}) *****-#{resident.phone_number.last(4)}"%></td>
      <td> <%= address.city %> </td>
      <td> <%= address.state %> </td>
      <td> <%= resident.active ? "Ativo" : "Inativo" %> </td>
      <td width="10%">
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Opções
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <li><%= link_to "Editar", edit_resident_path(resident.id) %></li>
            <li><%= link_to resident.active ? "Desativar" : "Ativar", status_resident_path(resident.id), method: :post %></li>
          </ul>
        </div>
      </td>
    </tr>
    <% end %>
</table>

<%= link_to "Criar novo Municipe", new_resident_path %>

<style>
  #residents {
    font-family: Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
    margin-bottom: 50px
  }

  #residents td, #residents th {
    border: 1px solid #ddd;
    padding: 8px;
  }

  #residents tr:nth-child(even){background-color: #f2f2f2;}

  #residents tr:hover {background-color: #ddd;}

  #residents th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #606868;
    color: white;
  }
</style>

app/views/residents/new.html.erb
<%= render "form" %>